const asset=name=>`assets/${name}`;
const gazebos=[
 {id:'gazebo-1',name:'Беседка 01',subtitle:'Горизонтальные линии · дерево',size:'5,30 × 3,60 м',height:'3,10 м',image:'gazebo-1-1.jpeg',images:[1,2,3].map(n=>`gazebo-1-${n}.jpeg`)},
 {id:'gazebo-2',name:'Беседка 02',subtitle:'Двускатная кровля · светлое дерево',size:'5,35 × 3,60 м',height:'3,55 м',image:'gazebo-2-1.jpeg',images:[1,2,3].map(n=>`gazebo-2-${n}.jpeg`)},
 {id:'gazebo-3',name:'Беседка 03',subtitle:'Односкатная кровля · тёмное дерево',size:'5,35 × 3,60 м',height:'3,10 м',image:'gazebo-3-1.jpeg',images:[1,2,3].map(n=>`gazebo-3-${n}.jpeg`)},
 {id:'gazebo-4',name:'Беседка 04',subtitle:'Открытая конструкция · дерево',size:'5,44 × 3,60 м',height:'3,30 м',image:'gazebo-4-1.jpeg',images:[1,2,3].map(n=>`gazebo-4-${n}.jpeg`)}
];
const kitchens=[1,2,3,4].map(n=>({id:`kitchen-${n}`,name:`Летняя кухня 0${n}`,subtitle:'Открытое и закрытое исполнение',image:`kitchen-${n}-open.jpeg`,images:[`kitchen-${n}-open.jpeg`,`kitchen-${n}-closed.jpeg`]}));
const fences=[1,2,3].map((n,i)=>({id:`fence-${n}`,name:`Забор 0${n}`,subtitle:['Горизонтальный · тёмные ламели','Вертикальный · светлое дерево','Дерево и бетон'][i],image:`fence-${n}-1.jpeg`,images:[1,2,3].map(j=>`fence-${n}-${j}.jpeg`)}));
const hearths=['Уличный камин','Костровая чаша','Мангал'].map((name,i)=>({id:`hearth-${i+1}`,name,subtitle:'Дерево, огонь и время на свежем воздухе',panel:i,concept:true}));
const groups={gazebos:{name:'Беседки и летние кухни',desc:'Выберите архитектуру из наших проектов. Размеры, материалы и комплектацию обсудим под ваш участок.',items:[...gazebos,...kitchens]},fences:{name:'Заборы',desc:'Горизонтальные и вертикальные линии. Дерево и металл в одном стиле с вашим домом.',items:fences},hearths:{name:'Камины и костровые чаши',desc:'Очаг для террасы и сада. Представлены концепции — конструкцию и комплектацию согласуем перед изготовлением.',items:hearths}};
const verandas=[1,3,6,8,11,13].map((page,i)=>({id:`veranda-${i+1}`,name:`Веранда 0${Math.floor(i/2)+1} · ${i%2?'с остеклением':'открытая'}`,subtitle:'Для кафе и ресторанов',image:`veranda-${page}.jpeg`,images:[`veranda-${page}.jpeg`]}));
groups.verandas={name:'Веранды для кафе и ресторанов',desc:'Оригинальные проекты коммерческих веранд. Три архитектурных решения в открытом исполнении и с остеклением.',items:verandas};
const all=[...gazebos,...kitchens,...fences,...hearths,...verandas];
function visual(item,cls=''){return item.panel!==undefined?`<div class="hearth-crop p${item.panel} ${cls}" role="img" aria-label="${item.name}"></div>`:`<img src="${asset(item.image)}" alt="${item.name} — ${item.subtitle}" loading="lazy" width="1071" height="647">`}
function card(item){return `<article class="card"><a class="card-image" href="product.html?model=${item.id}" aria-label="Подробнее: ${item.name}">${visual(item,'card-image')}</a><a class="card-info" href="product.html?model=${item.id}"><div><h3>${item.name}</h3><p>${item.size||item.subtitle}</p></div><span class="arrow" aria-hidden="true">↗</span></a></article>`}
function selector(){return `<div class="selector"><div class="selector-copy"><span class="eyebrow">Летние кухни</span><h3>Открытая или закрытая</h3><p>Один проект. Два варианта исполнения.<br>Сравните и выберите свой.</p><div class="model-tabs" aria-label="Модель летней кухни">${[1,2,3,4].map(n=>`<button type="button" data-kitchen="${n}" class="${n===1?'active':''}" aria-pressed="${n===1}">0${n}</button>`).join('')}</div><a id="kitchen-link" class="text-link" href="product.html?model=kitchen-1">Подробнее об этой модели ↗</a></div><div class="selector-visual"><img id="kitchen-image" src="assets/kitchen-1-open.jpeg" alt="Летняя кухня 01 — открытое исполнение" loading="lazy" width="993" height="603"><div class="state-tabs" aria-label="Исполнение"><button type="button" data-state="open" class="active" aria-pressed="true">Открыто</button><button type="button" data-state="closed" aria-pressed="false">Закрыто</button></div></div></div>`}
function section(key,num,items,extra=''){return `<section class="category ${key==='fences'?'soft':''}" id="${key}"><div class="wrap"><div class="section-head"><div><span class="eyebrow">0${num} / Коллекция</span><h2>${groups[key].name}</h2></div><a class="button" href="catalog.html?category=${key}">Посмотреть все проекты <span aria-hidden="true">↗</span></a></div><div class="cards">${items.map(card).join('')}</div>${extra}</div></section>`}
function contact(model=''){return `<section class="contact" id="inquiry"><div class="wrap contact-grid"><div><h2>Вопросы перед заказом</h2>${[
 ['Нужно ли готовить основание?','Требования к основанию зависят от выбранной конструкции и участка. Согласуем их при обсуждении проекта до начала работ.'],
 ['Можно ли изменить размеры?','Изготавливаем под заказ. Возможные изменения размеров, отделки и комплектации обсудим на основе выбранной модели.'],
 ['Как определяется стоимость?','По размерам, материалам, комплектации и условиям установки. Итоговый состав работ фиксируется в индивидуальном расчёте.'],
 ['Как организованы доставка и монтаж?','Укажите населённый пункт в Молдове и условия подъезда. Возможность, стоимость и сроки доставки и монтажа согласуются отдельно.']
 ].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div><div><h2>Обсудим ваш проект?</h2><p class="form-intro">Выберите модель и расскажите, что хотите изменить.</p><form id="lead-form"><div class="fields"><label><span>Ваше имя</span><input name="name" autocomplete="name" required maxlength="80" placeholder="Как к вам обращаться"></label><label><span>Телефон</span><input name="phone" type="tel" autocomplete="tel" required minlength="6" maxlength="35" placeholder="+373"></label></div><label><span class="sr-only">Описание проекта</span><textarea name="project" aria-label="Описание проекта" placeholder="Модель, размеры, населённый пункт" maxlength="2000">${model}</textarea></label><p class="form-note">Демонстрационная версия: запрос можно скачать. Отправка в WOODLAB будет доступна после подключения контактов.</p><button class="button" type="submit">Скачать запрос <span aria-hidden="true">↓</span></button><p class="form-status" role="status"></p></form></div></div></section>`}
function home(){return `<section class="hero"><div class="wrap"><div class="hero-grid"><div class="hero-copy"><span class="eyebrow">Дерево и металл · Молдова</span><h1>Ваше пространство.<br>Ваш характер.</h1><p>Беседки, летние кухни, заборы и очаги. Изготовление под заказ.</p><a class="button" href="#gazebos">Выбрать проект <span aria-hidden="true">↗</span></a></div><div class="hero-visual"><img src="assets/hero.png" alt="Беседка 01 — оригинальная модель WOODLAB" width="1920" height="768" fetchpriority="high"><p class="caption">БЕСЕДКА 01 / ПРОЕКТ ИЗ КАТАЛОГА WOODLAB</p></div></div><div class="hero-meta"><span>01 / Индивидуальные размеры</span><span>02 / Дерево и металл</span><span>03 / Открытые и закрытые решения</span></div></div></section>${section('gazebos',1,gazebos.slice(0,3),selector())}${section('fences',2,fences)}${section('hearths',3,hearths)}<section class="materials" id="materials"><div class="wrap material-grid"><div class="material-photo" role="img" aria-label="Фактура древесины из каталога WOODLAB"></div><div class="material-copy"><span class="eyebrow">Внимание к деталям</span><h2>Характер —<br>в материалах.</h2><p><span>01</span><span><b>Дерево</b><small>Фактура, оттенок и направление ламелей определяют внешний вид проекта.</small></span></p><p><span>02</span><span><b>Металл</b><small>Чёткие линии каркаса и матовая отделка. Цвет согласуем под ваш проект.</small></span></p><p><span>03</span><span><b>Один стиль</b><small>Беседка, забор и зона отдыха могут стать частью единого решения.</small></span></p></div></div></section><section class="process" id="process"><div class="wrap"><span class="eyebrow">Простой путь к вашему проекту</span><h2>От идеи до установки</h2><div class="steps">${[['Обсуждение','Выбираем модель, размеры и комплектацию.'],['Проект и расчёт','Согласуем внешний вид, состав работ и стоимость.'],['Изготовление','Создаём конструкцию по согласованному проекту.'],['Установка','Заранее согласуем основание, доставку и монтаж.']].map(([h,p],i)=>`<div><div class="step-number">0${i+1}</div><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></div></section>${contact()}`}
const params=new URLSearchParams(location.search);const main=document.querySelector('main');
if(location.pathname.endsWith('catalog.html')){
 const key=params.get('category')||'gazebos',g=groups[key];
 if(!g){main.innerHTML='<div class="wrap empty"><h1>Раздел не найден</h1><a class="text-link" href="index.html">На главную</a></div>'}
 else {document.title=`${g.name} — WOODLAB.MD`;main.innerHTML=`<section class="category-banner"><div class="wrap"><div class="breadcrumbs"><a href="index.html">Главная</a> / ${g.name}</div><span class="eyebrow">Коллекция WOODLAB</span><h1>${g.name}</h1><p>${g.desc}</p></div></section><section class="catalog-list"><div class="wrap">${key==='gazebos'?'<div class="filters"><button class="active" data-filter="all" aria-pressed="true">Все проекты</button><button data-filter="gazebo" aria-pressed="false">Беседки</button><button data-filter="kitchen" aria-pressed="false">Летние кухни</button></div>':''}<div class="cards" id="catalog-cards">${g.items.map(card).join('')}</div></div></section>${contact()}`;
 document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelector('#catalog-cards').innerHTML=g.items.filter(i=>b.dataset.filter==='all'||i.id.startsWith(b.dataset.filter)).map(card).join('')}));}
}else if(location.pathname.endsWith('product.html')){
 const item=all.find(x=>x.id===params.get('model'));
 if(!item){main.innerHTML='<div class="wrap empty"><h1>Модель не найдена</h1><a class="text-link" href="catalog.html?category=gazebos">К каталогу</a></div>'}
 else{const key=item.id.startsWith('fence')?'fences':item.concept?'hearths':'gazebos';document.title=`${item.name} на заказ — WOODLAB.MD`;main.innerHTML=`<div class="wrap product"><div class="breadcrumbs"><a href="index.html">Главная</a> / <a href="catalog.html?category=${key}">${groups[key].name}</a> / ${item.name}</div><div class="product-grid"><div>${item.concept?visual(item,'product-image'):`<button class="product-image" id="zoom" aria-label="Увеличить фото ${item.name}">${visual(item)}</button><p class="caption">НАЖМИТЕ НА ИЗОБРАЖЕНИЕ, ЧТОБЫ УВЕЛИЧИТЬ</p><div class="thumbs">${item.images.map((src,i)=>`<button data-photo="${src}" aria-label="Изображение ${i+1}"><img src="${asset(src)}" alt="${item.name}, изображение ${i+1}"></button>`).join('')}</div>`}</div><div class="product-copy"><span class="eyebrow">${item.concept?'Концепция очага':'Проект WOODLAB'} / Под заказ</span><h1>${item.name}</h1><p>${item.subtitle}</p><dl class="specs">${item.size?`<div><dt>Размеры по проекту</dt><dd>${item.size}</dd></div><div><dt>Высота</dt><dd>${item.height}</dd></div>`:''}<div><dt>Изготовление</dt><dd>Под заказ</dd></div><div><dt>Стоимость</dt><dd>По расчёту</dd></div></dl><a class="button" href="#inquiry">Обсудить эту модель ↗</a></div></div><div class="product-description"><h2>Основа для вашего проекта</h2><p>${item.concept?'Изображение показывает концепцию. Размеры, толщину металла, конструкцию и комплектацию необходимо согласовать перед изготовлением.':'Оригинальная модель из каталога WOODLAB. Размеры, отделку и комплектацию можно обсудить под ваш участок. Изображения показывают архитектурный проект; предметы интерьера не подразумеваются включёнными в стоимость.'}</p><p>Основание, доставка, монтаж и сроки указываются в индивидуальном предложении.</p></div></div>${contact(item.name)}`;
 const zoom=document.querySelector('#zoom');if(zoom){document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{zoom.querySelector('img').src=asset(b.dataset.photo)}));zoom.addEventListener('click',()=>{const dialog=document.querySelector('#gallery');dialog.querySelector('img').src=zoom.querySelector('img').src;dialog.querySelector('img').alt=item.name;dialog.querySelector('p').textContent=item.name;dialog.showModal()})}}
}else{main.innerHTML=home()}
const verandaLink='<a class="text-link" href="catalog.html?category=verandas">Веранды для кафе и ресторанов ↗</a>';
document.querySelector('.selector')?.insertAdjacentHTML('afterend',verandaLink);
if(location.pathname.endsWith('catalog.html')&&params.get('category')==='gazebos')document.querySelector('.filters')?.insertAdjacentHTML('afterend',`<p style="margin-bottom:28px">${verandaLink}</p>`);
let kitchen=1,state='open';function updateKitchen(){const img=document.querySelector('#kitchen-image');img.src=asset(`kitchen-${kitchen}-${state}.jpeg`);img.alt=`Летняя кухня 0${kitchen} — ${state==='open'?'открытое':'закрытое'} исполнение`;document.querySelector('#kitchen-link').href=`product.html?model=kitchen-${kitchen}`;document.querySelectorAll('[data-kitchen]').forEach(b=>{const active=Number(b.dataset.kitchen)===kitchen;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});document.querySelectorAll('[data-state]').forEach(b=>{const active=b.dataset.state===state;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
document.querySelectorAll('[data-kitchen]').forEach(b=>b.addEventListener('click',()=>{kitchen=Number(b.dataset.kitchen);updateKitchen()}));document.querySelectorAll('[data-state]').forEach(b=>b.addEventListener('click',()=>{state=b.dataset.state;updateKitchen()}));
document.querySelector('.menu').addEventListener('click',e=>{const open=document.querySelector('#navigation').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
const dialog=document.querySelector('#gallery');dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelector('#lead-form')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);const text=`Запрос WOODLAB.MD\nИмя: ${d.get('name')}\nТелефон: ${d.get('phone')}\nПроект: ${d.get('project')}\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='woodlab-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('.form-status').textContent='Запрос сохранён в файл. В WOODLAB он пока не отправлен.'});
